message(QT_PREFIX=$$[QT_INSTALL_PREFIX])
message(QT_LIBS=$$[QT_INSTALL_LIBS])
message(QT_BINS=$$[QT_INSTALL_BINS])
message(QT_INCS=$$[QT_INSTALL_HEADERS])
contains(QT_CONFIG,embedded):error(Cannot use Qt Embedded as the system Qt!)
