#ifndef _CHGLED_H_
#define	_CHGLED_H_
//#define GPIO119_CHG_LED		119
#define	CHGLED_DEV_MAJOR		251

typedef enum {BT400MS=0,BT1000MS,BT1200MS,BT2000MS,BT2600MS,BT4000MS,BT6000MS,BT8000MS}led_blink_time_t;
typedef enum {LT50MS=0,LT100MS,LT200MS,LT500MS,LT50MS_ALTER,LT100MS_ALTER,LT200MS_ALTER,LTCON_LIGHT}led_light_time_t;
typedef	enum {CON_HIGH=0,LED1_CTL,LED2_CTL,PWM_CTL,BATOK_CTL,CLK32_CTL,CHGDET_CTL,CON_LOW}led_ctl_t;

#define	MAX_ACT_CTRL		0x7
//#define	MAX_STD_CTRL		0x7
#define	MAX_LED1_BLINK_TIME	0x7
#define	MAX_LED1_LIGHT_TIME	0x7
#define	MAX_LED2_BLINK_TIME	0x7
#define	MAX_LED2_LIGHT_TIME	0x7

#define	ACT_MASK	0xF8
#define	STD_MASK	0xC7
#define	LED_BLINK_TIME_MASK	0xF8
#define	LED_LIGHT_TIME_MASK	0xC7
#define	LED_CHG_MASK	0xBF
#define	LED_ACT_MASK	0x7F

#define	SET_GPO0_CTRL			((CHGLED_DEV_MAJOR<<8)+0x1)
#define	SET_GPO1_CTRL			((CHGLED_DEV_MAJOR<<8)+0x2)

//#define	ACTIVE_STATE_USE		((CHGLED_DEV_MAJOR<<8)+0x10)
//#define	STANDBY_STATE_USE		((CHGLED_DEV_MAJOR<<8)+0x11)
//#define	BOTH_STATE_USE			((CHGLED_DEV_MAJOR<<8)+0x12)

#define	SET_LED1_BLINK_TIME		((CHGLED_DEV_MAJOR<<8)+0x20)
#define	SET_LED1_LIGHT_TIME		((CHGLED_DEV_MAJOR<<8)+0x21)
//#define	SET_LED1_CONSTANT_LIGHT		((CHGLED_DEV_MAJOR<<8)+0x22)
//#define	SET_LED1_CONSTANT_DIE		((CHGLED_DEV_MAJOR<<8)+0x23)
#define	SET_LED2_BLINK_TIME		((CHGLED_DEV_MAJOR<<8)+0x24)
#define	SET_LED2_LIGHT_TIME		((CHGLED_DEV_MAJOR<<8)+0x25)
//#define	SET_LED2_CONSTANT_LIGHT		((CHGLED_DEV_MAJOR<<8)+0x26)
//#define	SET_LED2_CONSTANT_DIE		((CHGLED_DEV_MAJOR<<8)+0x27)

#define	ENABLE_LED1_CHG_CONN		((CHGLED_DEV_MAJOR<<8)+0x30)
#define	DISABLE_LED1_CHG_CONN		((CHGLED_DEV_MAJOR<<8)+0x31)
#define	ENABLE_LED2_CHG_CONN		((CHGLED_DEV_MAJOR<<8)+0x32)
#define	DISABLE_LED2_CHG_CONN		((CHGLED_DEV_MAJOR<<8)+0x33)
#define	ENABLE_LED1_IN_ACT		((CHGLED_DEV_MAJOR<<8)+0x34)
#define	DISABLE_LED1_IN_ACT		((CHGLED_DEV_MAJOR<<8)+0x35)
#define	ENABLE_LED2_IN_ACT		((CHGLED_DEV_MAJOR<<8)+0x36)
#define	DISABLE_LED2_IN_ACT		((CHGLED_DEV_MAJOR<<8)+0x37)

#endif //

