#!/bin/sh
export TOOLCHAIN=/opt/toolchains/greenphone/gcc-4.1.1-glibc-2.3.6/arm-linux
USE_TB=1
TB_CC_PREFIX=arm-linux-
TB_CC_VER=auto
TB_SYS=arm:greenphone
export PKG_CONFIG_PREFIX=$TOOLCHAIN/arm-linux
export PKG_CONFIG_PATH=$PKG_CONFIG_PREFIX/lib/pkgconfig
