TEMPLATE=app
CONFIG+=qtopia unittest
SOURCEPATH+=/src/libraries/qtopiamedia
QTOPIA*=media
TARGET=tst_qmediacontentcontext
SOURCES+=tst_qmediacontentcontext.cpp
#VPATH+=$$QTOPIA_DEPOT_PATH/src/libraries/qtopiamedia
#SOURCES+=qmediatools.cpp
#HEADERS+=qmediatools.h
