#!/bin/sh
if [ -e  /sys/devices/platform/s3c2410-i2c/i2c-adapter/i2c-0/0-0008 ]; then 
    echo -n "fast_cccv" > /sys/devices/platform/s3c2410-i2c/i2c-adapter/i2c-0/0-0008/chgmode
fi

if [ -e  /sys/devices/platform/s3c2440-i2c/i2c-adapter/i2c-0/0-0073 ]; then
    echo -n "fast" > /sys/devices/platform/s3c2440-i2c/i2c-adapter/i2c-0/0-0073/chgmode
fi

