#!/bin/sh

# This script defines rule(s) for the root filesystem

# need to make busybox readonly so it can inherit
# ACL's from packagemanager to delete packages
lidsconf -A -o /bin/busybox -j READONLY
