#!/bin/sh
test -x $1 || { echo "Usage: $0 <executable> <sandbox dir>"; exit 1; }
test -d $2 || { echo "Usage: $0 <executable> <sandbox dir>"; exit 1; }

lidsconf -A -o $1 -j READONLY
lidsconf -A -s $QTOPIA_DIR/plugins/application/libpackagemanager.so -o $1 -i 1 -j WRITE
lidsconf -A -s $1 -o LIDS_SANDBOX -j ENABLE
lidsconf -A -s $1 -o $2 -j WRITE
lidsconf -A -s $1 -o "$2/bin" -j READONLY
